### ISSUE TITLE
index.js file missing

### ISSUE THREAD

**Issue by avinash10530** [payabbhi/superheroes-node#2]
index.js file missing from root directory which is mentioned in package,json file main:'index.js',in order to run the project.

please assist.

Thanks.

**Comment by ppm-shwetav** [comment]
Hey Avinash,

You should be able to run the sample app just fine without "index.js". 
Are you facing any issues when following the steps as given in the ReadMe?

Thanks,
Shwetav

**Comment by avinash10530** [comment]
Hii,
Thanks for the info.
As per your instruction i am following the steps and it is working fine.

Thanks,
Avinash
